apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- training-job-patch.yaml
resources:
- ../../base
images:
- name: ghcr.io/kimjunil/mnist_classifier
  newTag: 0.0.74
- name: ghcr.io/kimjunil/mnist_classifier_bento
  newTag: 0.0.70
