apiVersion: batch/v1
kind: CronJob
metadata:
  name: mnist-train-job
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
          - name: mnist-classifier
            image: ghcr.io/kimjunil/mnist_classifier:0.0.1
            args: ["--epochs", "1"]
          restartPolicy: Never